version: "3.8"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    networks:
      - mynetwork
  backend:
    build:
      context: ./backend
      dockerfile: HRIS/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge